defmodule RegentPoints.Repo.Migrations.InitialPoints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS regent_points")

    create table(:accounts, primary_key: false, prefix: "regent_points") do
      add(
        :id,
        references(:platform_human_users,
          column: :id,
          name: "accounts_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ),
        primary_key: true,
        null: false
      )
    end

    create unique_index(:accounts, [:id],
             name: "accounts_canonical_account_index",
             prefix: "regent_points"
           )

    alter table(:accounts, prefix: "regent_points") do
      add(:nft_count, :bigint)
      add(:nft_block, :bigint)
      add(:nft_block_hash, :text)
      add(:nft_checked_at, :utc_datetime_usec)
      add(:wallet_digest, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:accounts, :holdings_nonnegative,
             check: """
               nft_count IS NULL OR nft_count >= 0
             """,
             prefix: "regent_points"
           )

    execute("CREATE SCHEMA IF NOT EXISTS regent_points")

    create table(:nft_transfer_cursors, primary_key: false, prefix: "regent_points") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:chain_id, :bigint, null: false)
      add(:next_block, :bigint, null: false)
      add(:previous_hash, :text)
      add(:stopped_at, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:nft_transfer_cursors, [:chain_id],
             name: "nft_transfer_cursors_chain_index",
             prefix: "regent_points"
           )

    execute("CREATE SCHEMA IF NOT EXISTS regent_points")

    create table(:point_cap_usage, primary_key: false, prefix: "regent_points") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:account_id, :bigint, null: false)
      add(:program_id, :text, null: false)
      add(:cap_scope, :text, null: false)
      add(:window_start, :date, null: false)
      add(:window_end, :date)
      add(:award_count, :bigint, null: false, default: 0)
      add(:points_micro, :bigint, null: false, default: 0)
    end

    create unique_index(:point_cap_usage, [:account_id, :program_id, :cap_scope, :window_start],
             name: "point_cap_usage_allowance_index",
             prefix: "regent_points"
           )

    create constraint(:point_cap_usage, :cap_nonnegative,
             check: """
               award_count >= 0 AND points_micro >= 0
             """,
             prefix: "regent_points"
           )

    execute("CREATE SCHEMA IF NOT EXISTS regent_points")

    create table(:point_entries, primary_key: false, prefix: "regent_points") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:program_id, :text, null: false)

      add(
        :account_id,
        references(:accounts,
          column: :id,
          name: "point_entries_account_id_fkey",
          type: :bigint,
          prefix: "regent_points"
        ),
        null: false
      )

      add(:event_id, :uuid, null: false)
      add(:award_key, :text, null: false)
    end

    create unique_index(:point_entries, [:program_id, :award_key],
             name: "point_entries_logical_award_index",
             prefix: "regent_points"
           )

    alter table(:point_entries, prefix: "regent_points") do
      add(:rule_id, :text, null: false)
      add(:rule_version, :bigint, null: false)
      add(:source_app, :text, null: false)
      add(:actor_kind, :text, null: false)
      add(:actor_id, :text, null: false)
      add(:category, :text, null: false)
      add(:milestone_key, :text)
      add(:base_points_micro, :bigint, null: false)
      add(:bonus_points_micro, :bigint, null: false)
      add(:cap_reduction_micro, :bigint, null: false, default: 0)
      add(:bonus_percent, :bigint, null: false)
      add(:points_micro_delta, :bigint, null: false)
      add(:purchased_usdc_atomic, :bigint)
      add(:earned_at, :utc_datetime_usec, null: false)

      add(:recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :reversal_of_entry_id,
        references(:point_entries,
          column: :id,
          name: "point_entries_reversal_of_entry_id_fkey",
          type: :uuid,
          prefix: "regent_points"
        )
      )

      add(:reason_code, :text, null: false)
    end

    create index(:point_entries, [:account_id, :recorded_at], prefix: "regent_points")

    create index(:point_entries, [:reversal_of_entry_id], prefix: "regent_points")

    execute("CREATE SCHEMA IF NOT EXISTS regent_points")

    create table(:point_events, primary_key: false, prefix: "regent_points") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:point_entries, prefix: "regent_points") do
      modify(
        :event_id,
        references(:point_events, column: :id, name: "point_entries_event_id_fkey", type: :uuid)
      )
    end

    create constraint(:point_entries, :entry_amount_parts,
             check: """
               points_micro_delta = base_points_micro + bonus_points_micro
             """,
             prefix: "regent_points"
           )

    create constraint(:point_entries, :entry_direction,
             check: """
               (reversal_of_entry_id IS NULL AND base_points_micro >= 0 AND bonus_points_micro >= 0) OR (reversal_of_entry_id IS NOT NULL AND base_points_micro < 0 AND bonus_points_micro <= 0)
             """,
             prefix: "regent_points"
           )

    create constraint(:point_entries, :entry_bonus_tier,
             check: """
               bonus_percent IN (0,20,45,75)
             """,
             prefix: "regent_points"
           )

    create constraint(:point_entries, :entry_cap_nonnegative,
             check: """
               cap_reduction_micro >= 0
             """,
             prefix: "regent_points"
           )

    alter table(:point_events, prefix: "regent_points") do
      add(:program_id, :text, null: false)
      add(:source_app, :text, null: false)
      add(:source_kind, :text, null: false)
      add(:source_event_key, :text, null: false)
      add(:rule_id, :text, null: false)

      add(
        :account_id,
        references(:accounts,
          column: :id,
          name: "point_events_account_id_fkey",
          type: :bigint,
          prefix: "regent_points"
        ),
        null: false
      )
    end

    create unique_index(
             :point_events,
             [:program_id, :source_app, :source_kind, :source_event_key, :rule_id],
             name: "point_events_source_rule_index",
             prefix: "regent_points"
           )

    alter table(:point_events, prefix: "regent_points") do
      add(:actor_kind, :text, null: false)
      add(:actor_id, :text, null: false)
      add(:source_action_at, :utc_datetime_usec, null: false)
      add(:qualified_at, :utc_datetime_usec, null: false)
      add(:evidence_ref, :text, null: false)
      add(:payload_digest, :text, null: false)
      add(:evidence, :map, null: false)
      add(:rule_snapshot, :map, null: false)
      add(:wallets, {:array, :text}, null: false)
      add(:bonus_percent, :bigint)
      add(:nft_block, :bigint)
      add(:nft_block_hash, :text)
      add(:nft_count, :bigint)
      add(:award_key, :text, null: false)
      add(:processing_status, :text, null: false, default: "pending")
      add(:processed_at, :utc_datetime_usec)
      add(:reason_code, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:point_events, [:account_id, :processing_status], prefix: "regent_points")

    execute("CREATE SCHEMA IF NOT EXISTS regent_points")

    create table(:source_rejections, primary_key: false, prefix: "regent_points") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:source, :map, null: false)
      add(:reason_code, :text, null: false)
      add(:rejection_key, :text, null: false)

      add(:recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:source_rejections, [:rejection_key],
             name: "source_rejections_rejected_source_index",
             prefix: "regent_points"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:source_rejections, [:rejection_key],
        name: "source_rejections_rejected_source_index",
        prefix: "regent_points"
      )
    )

    drop(table(:source_rejections, prefix: "regent_points"))

    drop_if_exists(
      index(:point_events, [:account_id, :processing_status], prefix: "regent_points")
    )

    drop(constraint(:point_events, "point_events_account_id_fkey", prefix: "regent_points"))

    alter table(:point_events, prefix: "regent_points") do
      remove(:inserted_at)
      remove(:reason_code)
      remove(:processed_at)
      remove(:processing_status)
      remove(:award_key)
      remove(:nft_count)
      remove(:nft_block_hash)
      remove(:nft_block)
      remove(:bonus_percent)
      remove(:wallets)
      remove(:rule_snapshot)
      remove(:evidence)
      remove(:payload_digest)
      remove(:evidence_ref)
      remove(:qualified_at)
      remove(:source_action_at)
      remove(:actor_id)
      remove(:actor_kind)
    end

    drop_if_exists(
      unique_index(
        :point_events,
        [:program_id, :source_app, :source_kind, :source_event_key, :rule_id],
        name: "point_events_source_rule_index",
        prefix: "regent_points"
      )
    )

    alter table(:point_events, prefix: "regent_points") do
      remove(:account_id)
      remove(:rule_id)
      remove(:source_event_key)
      remove(:source_kind)
      remove(:source_app)
      remove(:program_id)
    end

    drop_if_exists(constraint(:point_entries, :entry_cap_nonnegative, prefix: "regent_points"))

    drop_if_exists(constraint(:point_entries, :entry_bonus_tier, prefix: "regent_points"))

    drop_if_exists(constraint(:point_entries, :entry_direction, prefix: "regent_points"))

    drop_if_exists(constraint(:point_entries, :entry_amount_parts, prefix: "regent_points"))

    drop(
      constraint(:point_entries, "point_entries_reversal_of_entry_id_fkey",
        prefix: "regent_points"
      )
    )

    drop(constraint(:point_entries, "point_entries_event_id_fkey", prefix: "regent_points"))

    drop(constraint(:point_entries, "point_entries_account_id_fkey", prefix: "regent_points"))

    alter table(:point_entries, prefix: "regent_points") do
      modify(:event_id, :uuid)
    end

    drop(table(:point_events, prefix: "regent_points"))

    drop_if_exists(index(:point_entries, [:reversal_of_entry_id], prefix: "regent_points"))

    drop_if_exists(index(:point_entries, [:account_id, :recorded_at], prefix: "regent_points"))

    alter table(:point_entries, prefix: "regent_points") do
      remove(:reason_code)
      remove(:reversal_of_entry_id)
      remove(:recorded_at)
      remove(:earned_at)
      remove(:purchased_usdc_atomic)
      remove(:points_micro_delta)
      remove(:bonus_percent)
      remove(:cap_reduction_micro)
      remove(:bonus_points_micro)
      remove(:base_points_micro)
      remove(:milestone_key)
      remove(:category)
      remove(:actor_id)
      remove(:actor_kind)
      remove(:source_app)
      remove(:rule_version)
      remove(:rule_id)
    end

    drop_if_exists(
      unique_index(:point_entries, [:program_id, :award_key],
        name: "point_entries_logical_award_index",
        prefix: "regent_points"
      )
    )

    drop(table(:point_entries, prefix: "regent_points"))

    drop_if_exists(constraint(:point_cap_usage, :cap_nonnegative, prefix: "regent_points"))

    drop_if_exists(
      unique_index(:point_cap_usage, [:account_id, :program_id, :cap_scope, :window_start],
        name: "point_cap_usage_allowance_index",
        prefix: "regent_points"
      )
    )

    drop(table(:point_cap_usage, prefix: "regent_points"))

    drop_if_exists(
      unique_index(:nft_transfer_cursors, [:chain_id],
        name: "nft_transfer_cursors_chain_index",
        prefix: "regent_points"
      )
    )

    drop(table(:nft_transfer_cursors, prefix: "regent_points"))

    drop_if_exists(constraint(:accounts, :holdings_nonnegative, prefix: "regent_points"))

    drop(constraint(:accounts, "accounts_id_fkey", prefix: "regent_points"))

    alter table(:accounts, prefix: "regent_points") do
      remove(:inserted_at)
      remove(:wallet_digest)
      remove(:nft_checked_at)
      remove(:nft_block_hash)
      remove(:nft_block)
      remove(:nft_count)
    end

    drop_if_exists(
      unique_index(:accounts, [:id],
        name: "accounts_canonical_account_index",
        prefix: "regent_points"
      )
    )

    drop(table(:accounts, prefix: "regent_points"))
  end
end
