defmodule RegentPoints.Repo.Migrations.MonthBonusTally do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.
  `down/0` was ordered by hand, because the generated one added constraints before
  their columns and never recreated `nft_transfer_cursors`; do not regenerate it.
  """

  use Ecto.Migration

  def up do
    drop(table(:nft_transfer_cursors, prefix: "regent_points"))

    alter table(:accounts, prefix: "regent_points") do
      remove(:nft_block)
      remove(:nft_block_hash)
      remove(:nft_checked_at)
      remove(:wallet_digest)
    end

    drop_if_exists(constraint(:accounts, :holdings_nonnegative, prefix: "regent_points"))

    alter table(:accounts, prefix: "regent_points") do
      remove(:nft_count)
    end

    execute("CREATE SCHEMA IF NOT EXISTS regent_points")

    create table(:month_bonuses, primary_key: false, prefix: "regent_points") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:program_id, :text, null: false)

      add(
        :account_id,
        references(:accounts,
          column: :id,
          name: "month_bonuses_account_id_fkey",
          type: :bigint,
          prefix: "regent_points"
        ),
        null: false
      )

      add(:month, :bigint, null: false)
    end

    create unique_index(:month_bonuses, [:program_id, :account_id, :month],
             name: "month_bonuses_account_month_index",
             prefix: "regent_points"
           )

    alter table(:month_bonuses, prefix: "regent_points") do
      add(:earned_micro, :bigint, null: false)
      add(:nft_count, :bigint, null: false)
      add(:nft_block, :bigint, null: false)
      add(:bonus_percent, :bigint, null: false)
      add(:bonus_micro, :bigint, null: false)

      add(:tallied_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create constraint(:month_bonuses, :month_bonus_tier,
             check: """
               bonus_percent IN (0,20,45,75)
             """,
             prefix: "regent_points"
           )

    create constraint(:month_bonuses, :month_bonus_amount,
             check: """
               earned_micro >= 0 AND nft_count >= 0 AND bonus_micro = earned_micro * bonus_percent / 100
             """,
             prefix: "regent_points"
           )

    alter table(:point_entries, prefix: "regent_points") do
      remove(:bonus_points_micro)
    end

    drop_if_exists(constraint(:point_entries, :entry_amount_parts, prefix: "regent_points"))

    drop_if_exists(constraint(:point_entries, :entry_direction, prefix: "regent_points"))

    alter table(:point_entries, prefix: "regent_points") do
      remove(:base_points_micro)
    end

    drop_if_exists(constraint(:point_entries, :entry_bonus_tier, prefix: "regent_points"))

    alter table(:point_entries, prefix: "regent_points") do
      remove(:bonus_percent)
    end

    create constraint(:point_entries, :entry_direction,
             check: """
               (reversal_of_entry_id IS NULL AND points_micro_delta >= 0) OR (reversal_of_entry_id IS NOT NULL AND points_micro_delta < 0)
             """,
             prefix: "regent_points"
           )

    alter table(:point_events, prefix: "regent_points") do
      remove(:wallets)
      remove(:bonus_percent)
      remove(:nft_block)
      remove(:nft_block_hash)
      remove(:nft_count)
    end
  end

  # Rolls back only while the Points tables hold no awards: the restored columns have no values.
  def down do
    alter table(:point_events, prefix: "regent_points") do
      add(:wallets, {:array, :text}, null: false)
      add(:bonus_percent, :bigint)
      add(:nft_block, :bigint)
      add(:nft_block_hash, :text)
      add(:nft_count, :bigint)
    end

    drop(constraint(:point_entries, :entry_direction, prefix: "regent_points"))

    alter table(:point_entries, prefix: "regent_points") do
      add(:base_points_micro, :bigint, null: false)
      add(:bonus_points_micro, :bigint, null: false)
      add(:bonus_percent, :bigint, null: false)
    end

    create constraint(:point_entries, :entry_amount_parts,
             check: """
               points_micro_delta = base_points_micro + bonus_points_micro
             """,
             prefix: "regent_points"
           )

    create constraint(:point_entries, :entry_direction,
             check: """
               (reversal_of_entry_id IS NULL AND base_points_micro >= 0 AND bonus_points_micro >= 0) OR (reversal_of_entry_id IS NOT NULL AND base_points_micro < 0 AND bonus_points_micro <= 0)
             """,
             prefix: "regent_points"
           )

    create constraint(:point_entries, :entry_bonus_tier,
             check: """
               bonus_percent IN (0,20,45,75)
             """,
             prefix: "regent_points"
           )

    drop(table(:month_bonuses, prefix: "regent_points"))

    alter table(:accounts, prefix: "regent_points") do
      add(:nft_count, :bigint)
      add(:nft_block, :bigint)
      add(:nft_block_hash, :text)
      add(:nft_checked_at, :utc_datetime_usec)
      add(:wallet_digest, :text)
    end

    create constraint(:accounts, :holdings_nonnegative,
             check: """
               nft_count IS NULL OR nft_count >= 0
             """,
             prefix: "regent_points"
           )

    create table(:nft_transfer_cursors, primary_key: false, prefix: "regent_points") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:chain_id, :bigint, null: false)
      add(:next_block, :bigint, null: false)
      add(:previous_hash, :text)
      add(:stopped_at, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:nft_transfer_cursors, [:chain_id],
             name: "nft_transfer_cursors_chain_index",
             prefix: "regent_points"
           )
  end
end
