defmodule RegentCredits.TestRepo.Migrations.CreditsHistoryIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:transfers, [:from_account_id, :id],
             concurrently: true,
             prefix: "regent_credits"
           )

    create index(:transfers, [:to_account_id, :id], concurrently: true, prefix: "regent_credits")
  end

  def down do
    drop_if_exists(index(:transfers, [:to_account_id, :id], prefix: "regent_credits"))

    drop_if_exists(index(:transfers, [:from_account_id, :id], prefix: "regent_credits"))
  end
end
