defmodule RegentCredits.TestRepo.Migrations.CreditsPurchasesGiftsRefunds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:gifts, primary_key: false, prefix: "regent_credits") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:key, :text, null: false)
      add(:to, :text, null: false)
      add(:amount, :decimal, null: false)
      add(:note, :text)
      add(:given_by, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:gifts, [:key, :to], name: "gifts_key_to_index", prefix: "regent_credits")

    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:purchases, primary_key: false, prefix: "regent_credits") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:privy_user_id, :text, null: false)
      add(:wallet, :text, null: false)
      add(:chain, :text, null: false)
      add(:amount, :bigint, null: false)
      add(:number, :uuid, null: false)
      add(:tx_hash, :text, null: false)
      add(:status, :text, null: false, default: "checking")
      add(:reason, :text)
      add(:block_number, :bigint)
      add(:block_hash, :text)
      add(:credited_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:purchases, [:chain, :tx_hash],
             name: "purchases_credited_index",
             prefix: "regent_credits",
             where: "(status = 'credited')"
           )

    create unique_index(:purchases, [:privy_user_id, :chain, :tx_hash],
             name: "purchases_report_index",
             prefix: "regent_credits"
           )

    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:refunds, primary_key: false, prefix: "regent_credits") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:purchase_id, :uuid, null: false)
      add(:privy_user_id, :text, null: false)
      add(:wallet, :text, null: false)
      add(:chain, :text, null: false)
      add(:amount, :bigint, null: false)
      add(:status, :text, null: false, default: "locked")
      add(:tx_hash, :text)
      add(:started_by, :text, null: false)
      add(:sent_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:refunds, [:purchase_id],
             name: "refunds_purchase_index",
             prefix: "regent_credits"
           )

    create unique_index(:refunds, [:chain, :tx_hash],
             name: "refunds_transaction_index",
             prefix: "regent_credits"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:refunds, [:chain, :tx_hash],
        name: "refunds_transaction_index",
        prefix: "regent_credits"
      )
    )

    drop_if_exists(
      unique_index(:refunds, [:purchase_id],
        name: "refunds_purchase_index",
        prefix: "regent_credits"
      )
    )

    drop(table(:refunds, prefix: "regent_credits"))

    drop_if_exists(
      unique_index(:purchases, [:privy_user_id, :chain, :tx_hash],
        name: "purchases_report_index",
        prefix: "regent_credits"
      )
    )

    drop_if_exists(
      unique_index(:purchases, [:chain, :tx_hash],
        name: "purchases_credited_index",
        prefix: "regent_credits"
      )
    )

    drop(table(:purchases, prefix: "regent_credits"))

    drop_if_exists(
      unique_index(:gifts, [:key, :to], name: "gifts_key_to_index", prefix: "regent_credits")
    )

    drop(table(:gifts, prefix: "regent_credits"))
  end
end
