defmodule RegentCredits.TestRepo.Migrations.CreditsDepositReader do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:deposit_cursors, primary_key: false, prefix: "regent_credits") do
      add(:chain, :text, null: false, primary_key: true)
      add(:next_block, :bigint, null: false)

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    drop_if_exists(
      unique_index(:purchases, [:chain, :tx_hash],
        name: "purchases_credited_index",
        prefix: "regent_credits"
      )
    )

    drop_if_exists(
      unique_index(:purchases, [:privy_user_id, :chain, :tx_hash],
        name: "purchases_report_index",
        prefix: "regent_credits"
      )
    )

    create unique_index(:purchases, [:privy_user_id, :chain, :tx_hash, :wallet],
             name: "purchases_report_index",
             prefix: "regent_credits"
           )

    alter table(:purchases, prefix: "regent_credits") do
      modify(:privy_user_id, :text, null: true)
      modify(:amount, :decimal)
    end

    create unique_index(:purchases, [:chain, :tx_hash, :wallet],
             name: "purchases_credited_index",
             prefix: "regent_credits",
             where: "(status = 'credited')"
           )

    alter table(:refunds, prefix: "regent_credits") do
      modify(:amount, :decimal)
    end
  end

  def down do
    alter table(:refunds, prefix: "regent_credits") do
      modify(:amount, :bigint)
    end

    drop_if_exists(
      unique_index(:purchases, [:chain, :tx_hash, :wallet],
        name: "purchases_credited_index",
        prefix: "regent_credits"
      )
    )

    alter table(:purchases, prefix: "regent_credits") do
      modify(:amount, :bigint)
      modify(:privy_user_id, :text, null: false)
    end

    drop_if_exists(
      unique_index(:purchases, [:privy_user_id, :chain, :tx_hash, :wallet],
        name: "purchases_report_index",
        prefix: "regent_credits"
      )
    )

    create unique_index(:purchases, [:privy_user_id, :chain, :tx_hash],
             name: "purchases_report_index",
             prefix: "regent_credits"
           )

    create unique_index(:purchases, [:chain, :tx_hash],
             name: "purchases_credited_index",
             prefix: "regent_credits",
             where: "(status = 'credited')"
           )

    drop(table(:deposit_cursors, prefix: "regent_credits"))
  end
end
