defmodule RegentCredits.TestRepo.Migrations.RememberWallets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:wallets, primary_key: false, prefix: "regent_credits") do
      add(:address, :text, null: false, primary_key: true)
      add(:privy_user_id, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:wallets, [:privy_user_id], prefix: "regent_credits")
  end

  def down do
    drop_if_exists(index(:wallets, [:privy_user_id], prefix: "regent_credits"))

    drop(table(:wallets, prefix: "regent_credits"))
  end
end
