defmodule RegentCredits.TestRepo.Migrations.PurchaseLowercaseKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:purchases, :purchases_wallet_lowercase,
             check: """
               wallet ~ '^0x[0-9a-f]{40}$'
             """,
             prefix: "regent_credits"
           )

    create constraint(:purchases, :purchases_tx_hash_lowercase,
             check: """
               tx_hash ~ '^0x[0-9a-f]{64}$'
             """,
             prefix: "regent_credits"
           )
  end

  def down do
    drop_if_exists(constraint(:purchases, :purchases_tx_hash_lowercase, prefix: "regent_credits"))

    drop_if_exists(constraint(:purchases, :purchases_wallet_lowercase, prefix: "regent_credits"))
  end
end
