defmodule RegentCredits.TestRepo.Migrations.CreditsLedger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:accounts, primary_key: false, prefix: "regent_credits") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:identifier, :text, null: false)
      add(:currency, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:accounts, [:identifier],
        name: "accounts_unique_identifier_index",
        prefix: "regent_credits"
      )
    )

    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:agent_permissions, primary_key: false, prefix: "regent_credits") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:privy_user_id, :text, null: false)
      add(:agent_address, :text, null: false)
      add(:enabled, :boolean, null: false, default: false)
      add(:max_per_spend, :decimal, null: false)
      add(:daily_limit, :decimal, null: false)
      add(:sites, {:array, :text}, null: false, default: [])

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:agent_permissions, [:privy_user_id, :agent_address],
        name: "agent_permissions_agent_index",
        prefix: "regent_credits"
      )
    )

    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:balances, primary_key: false, prefix: "regent_credits") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:balance, :money_with_currency, null: false)
      add(:transfer_id, :binary, null: false)

      add(
        :account_id,
        references(:accounts,
          column: :id,
          name: "balances_account_id_fkey",
          type: :uuid,
          prefix: "regent_credits"
        ), null: false)
    end

    create(
      unique_index(:balances, [:account_id, :transfer_id],
        name: "balances_unique_references_index",
        prefix: "regent_credits"
      )
    )

    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:first_uses, primary_key: false, prefix: "regent_credits") do
      add(:privy_user_id, :text, null: false, primary_key: true)
      add(:hold_key, :text, null: false)

      add(:used_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:holds, primary_key: false, prefix: "regent_credits") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:site, :text, null: false)
      add(:key, :text, null: false)
      add(:privy_user_id, :text, null: false)
      add(:purpose, :text, null: false)
      add(:agent_address, :text)
      add(:amount, :decimal, null: false)
      add(:given, :decimal, null: false)
      add(:purchased, :decimal, null: false)
      add(:status, :text, null: false, default: "held")
      add(:returned, :decimal)
      add(:used, :decimal)
      add(:forfeited, :decimal)
      add(:carried_to, :text)
      add(:paid_to, :text)
      add(:reason, :text)
      add(:closed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:holds, [:site, :key], name: "holds_site_key_index", prefix: "regent_credits")
    )

    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:transfers, primary_key: false, prefix: "regent_credits") do
      add(:operation, :text, null: false)
      add(:id, :binary, null: false, primary_key: true)
    end

    alter table(:balances, prefix: "regent_credits") do
      modify(
        :transfer_id,
        references(:transfers,
          column: :id,
          name: "balances_transfer_id_fkey",
          type: :binary,
          on_delete: :delete_all
        )
      )
    end

    alter table(:transfers, prefix: "regent_credits") do
      add(:amount, :money_with_currency, null: false)

      add(:timestamp, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :from_account_id,
        references(:accounts,
          column: :id,
          name: "transfers_from_account_id_fkey",
          type: :uuid,
          prefix: "regent_credits"
        )
      )

      add(
        :to_account_id,
        references(:accounts,
          column: :id,
          name: "transfers_to_account_id_fkey",
          type: :uuid,
          prefix: "regent_credits"
        )
      )
    end

    execute("""
    CREATE FUNCTION regent_credits.refuse_change() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION 'regent_credits.% rows are final', TG_TABLE_NAME;
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER transfers_are_final BEFORE UPDATE OR DELETE ON regent_credits.transfers
      FOR EACH ROW EXECUTE FUNCTION regent_credits.refuse_change()
    """)
  end

  def down do
    execute("""
    DROP TRIGGER transfers_are_final ON regent_credits.transfers
    """)

    execute("""
    DROP FUNCTION regent_credits.refuse_change()
    """)

    drop(constraint(:transfers, "transfers_to_account_id_fkey", prefix: "regent_credits"))

    drop(constraint(:transfers, "transfers_from_account_id_fkey", prefix: "regent_credits"))

    alter table(:transfers, prefix: "regent_credits") do
      remove(:to_account_id)
      remove(:from_account_id)
      remove(:inserted_at)
      remove(:timestamp)
      remove(:amount)
    end

    drop(constraint(:balances, "balances_account_id_fkey", prefix: "regent_credits"))

    drop(constraint(:balances, "balances_transfer_id_fkey", prefix: "regent_credits"))

    alter table(:balances, prefix: "regent_credits") do
      modify(:transfer_id, :binary)
    end

    drop(table(:transfers, prefix: "regent_credits"))

    drop_if_exists(
      unique_index(:holds, [:site, :key], name: "holds_site_key_index", prefix: "regent_credits")
    )

    drop(table(:holds, prefix: "regent_credits"))

    drop(table(:first_uses, prefix: "regent_credits"))

    drop_if_exists(
      unique_index(:balances, [:account_id, :transfer_id],
        name: "balances_unique_references_index",
        prefix: "regent_credits"
      )
    )

    drop(table(:balances, prefix: "regent_credits"))

    drop_if_exists(
      unique_index(:agent_permissions, [:privy_user_id, :agent_address],
        name: "agent_permissions_agent_index",
        prefix: "regent_credits"
      )
    )

    drop(table(:agent_permissions, prefix: "regent_credits"))

    drop_if_exists(
      unique_index(:accounts, [:identifier],
        name: "accounts_unique_identifier_index",
        prefix: "regent_credits"
      )
    )

    drop(table(:accounts, prefix: "regent_credits"))
  end
end
