defmodule RegentCredits.TestRepo.Migrations.CreditsDepositReader do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS regent_credits")

    create table(:deposit_cursors, primary_key: false, prefix: "regent_credits") do
      add(:chain, :text, null: false, primary_key: true)
      add(:next_block, :bigint, null: false)

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    alter table(:purchases, prefix: "regent_credits") do
      modify(:privy_user_id, :text, null: true)
      modify(:amount, :decimal)
    end

    alter table(:refunds, prefix: "regent_credits") do
      modify(:amount, :decimal)
    end
  end

  def down do
    alter table(:refunds, prefix: "regent_credits") do
      modify(:amount, :bigint)
    end

    alter table(:purchases, prefix: "regent_credits") do
      modify(:amount, :bigint)
      modify(:privy_user_id, :text, null: false)
    end

    drop(table(:deposit_cursors, prefix: "regent_credits"))
  end
end
